version: 2.1
commands:
  do_all:
    steps:
      - run: git clone --recursive https://github.com/edwardstock/dockerpack .
      - run: bash cfg/package_make.sh -t archive
      - run: bash _build/package_upload.sh -t github

jobs:
  build_all:
    docker:
      - image: docker.edwardstock.com/gcc_dev_el7:latest
    steps:
      - do_all

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build_all
